package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DATA_FLAG".
 */
public class DataFlag {

    private Long id;
    private Boolean is;

    public DataFlag() {
    }

    public DataFlag(Long id) {
        this.id = id;
    }

    public DataFlag(Long id, Boolean is) {
        this.id = id;
        this.is = is;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIs() {
        return is;
    }

    public void setIs(Boolean is) {
        this.is = is;
    }

}
