package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DECIDE_ACTION".
 */
public class DecideAction {

    private Long id;
    private String action;
    private Boolean evaluation;
    private Long date;

    public DecideAction() {
    }

    public DecideAction(Long id) {
        this.id = id;
    }

    public DecideAction(Long id, String action, Boolean evaluation, Long date) {
        this.id = id;
        this.action = action;
        this.evaluation = evaluation;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public Boolean getEvaluation() {
        return evaluation;
    }

    public void setEvaluation(Boolean evaluation) {
        this.evaluation = evaluation;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

}
