package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Heart;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HEART".
*/
public class HeartDao extends AbstractDao<Heart, Long> {

    public static final String TABLENAME = "HEART";

    /**
     * Properties of entity Heart.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Hz = new Property(1, Double.class, "hz", false, "HZ");
        public final static Property Pow = new Property(2, Double.class, "pow", false, "POW");
        public final static Property HeatRate = new Property(3, Double.class, "heatRate", false, "HEAT_RATE");
        public final static Property Date = new Property(4, Long.class, "date", false, "DATE");
    };


    public HeartDao(DaoConfig config) {
        super(config);
    }
    
    public HeartDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HEART\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"HZ\" REAL," + // 1: hz
                "\"POW\" REAL," + // 2: pow
                "\"HEAT_RATE\" REAL," + // 3: heatRate
                "\"DATE\" INTEGER);"); // 4: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HEART\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Heart entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double hz = entity.getHz();
        if (hz != null) {
            stmt.bindDouble(2, hz);
        }
 
        Double pow = entity.getPow();
        if (pow != null) {
            stmt.bindDouble(3, pow);
        }
 
        Double heatRate = entity.getHeatRate();
        if (heatRate != null) {
            stmt.bindDouble(4, heatRate);
        }
 
        Long date = entity.getDate();
        if (date != null) {
            stmt.bindLong(5, date);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Heart readEntity(Cursor cursor, int offset) {
        Heart entity = new Heart( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // hz
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // pow
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // heatRate
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // date
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Heart entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHz(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setPow(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setHeatRate(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setDate(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Heart entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Heart entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
