package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECOMMEND".
 */
public class Recommend {

    private Long id;
    private String text;
    private Boolean evaluation;
    private Long date;

    public Recommend() {
    }

    public Recommend(Long id) {
        this.id = id;
    }

    public Recommend(Long id, String text, Boolean evaluation, Long date) {
        this.id = id;
        this.text = text;
        this.evaluation = evaluation;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Boolean getEvaluation() {
        return evaluation;
    }

    public void setEvaluation(Boolean evaluation) {
        this.evaluation = evaluation;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

}
